[build]
  command = ""
  publish = "."

[[redirects]]
  from = "/accept/*"
  to = "/accept/index.html"
  status = 200

[[redirects]]
  from = "/.netlify/identity/*"
  to = "/admin/index.html"
  status = 200

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200